// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.BaseDefine.proto

#include "IM.BaseDefine.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace IM {
namespace BaseDefine {
}  // namespace BaseDefine
}  // namespace IM
namespace IM {
namespace BaseDefine {
bool ServiceID_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> ServiceID_strings[9] = {};

static const char ServiceID_names[] =
  "SID_BUDDY_LIST"
  "SID_DEFAULT"
  "SID_FILE"
  "SID_GROUP"
  "SID_INTERNAL"
  "SID_LOGIN"
  "SID_MSG"
  "SID_OTHER"
  "SID_SWITCH_SERVICE";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry ServiceID_entries[] = {
  { {ServiceID_names + 0, 14}, 2 },
  { {ServiceID_names + 14, 11}, 0 },
  { {ServiceID_names + 25, 8}, 5 },
  { {ServiceID_names + 33, 9}, 4 },
  { {ServiceID_names + 42, 12}, 8 },
  { {ServiceID_names + 54, 9}, 1 },
  { {ServiceID_names + 63, 7}, 3 },
  { {ServiceID_names + 70, 9}, 7 },
  { {ServiceID_names + 79, 18}, 6 },
};

static const int ServiceID_entries_by_number[] = {
  1, // 0 -> SID_DEFAULT
  5, // 1 -> SID_LOGIN
  0, // 2 -> SID_BUDDY_LIST
  6, // 3 -> SID_MSG
  3, // 4 -> SID_GROUP
  2, // 5 -> SID_FILE
  8, // 6 -> SID_SWITCH_SERVICE
  7, // 7 -> SID_OTHER
  4, // 8 -> SID_INTERNAL
};

const std::string& ServiceID_Name(
    ServiceID value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          ServiceID_entries,
          ServiceID_entries_by_number,
          9, ServiceID_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      ServiceID_entries,
      ServiceID_entries_by_number,
      9, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     ServiceID_strings[idx].get();
}
bool ServiceID_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ServiceID* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      ServiceID_entries, 9, name, &int_value);
  if (success) {
    *value = static_cast<ServiceID>(int_value);
  }
  return success;
}
bool LoginCmdID_IsValid(int value) {
  switch (value) {
    case 0:
    case 257:
    case 258:
    case 259:
    case 260:
    case 261:
    case 262:
    case 263:
    case 264:
    case 265:
    case 266:
    case 267:
    case 268:
    case 269:
    case 270:
    case 271:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> LoginCmdID_strings[16] = {};

static const char LoginCmdID_names[] =
  "CID_LOGIN_KICK_USER"
  "CID_LOGIN_REQ_DEFAULT"
  "CID_LOGIN_REQ_DEVICETOKEN"
  "CID_LOGIN_REQ_KICKPCCLIENT"
  "CID_LOGIN_REQ_LOGINOUT"
  "CID_LOGIN_REQ_MSGSERVER"
  "CID_LOGIN_REQ_PUSH_SHIELD"
  "CID_LOGIN_REQ_QUERY_PUSH_SHIELD"
  "CID_LOGIN_REQ_USERLOGIN"
  "CID_LOGIN_RES_DEVICETOKEN"
  "CID_LOGIN_RES_KICKPCCLIENT"
  "CID_LOGIN_RES_LOGINOUT"
  "CID_LOGIN_RES_MSGSERVER"
  "CID_LOGIN_RES_PUSH_SHIELD"
  "CID_LOGIN_RES_QUERY_PUSH_SHIELD"
  "CID_LOGIN_RES_USERLOGIN";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry LoginCmdID_entries[] = {
  { {LoginCmdID_names + 0, 19}, 263 },
  { {LoginCmdID_names + 19, 21}, 0 },
  { {LoginCmdID_names + 40, 25}, 264 },
  { {LoginCmdID_names + 65, 26}, 266 },
  { {LoginCmdID_names + 91, 22}, 261 },
  { {LoginCmdID_names + 113, 23}, 257 },
  { {LoginCmdID_names + 136, 25}, 268 },
  { {LoginCmdID_names + 161, 31}, 270 },
  { {LoginCmdID_names + 192, 23}, 259 },
  { {LoginCmdID_names + 215, 25}, 265 },
  { {LoginCmdID_names + 240, 26}, 267 },
  { {LoginCmdID_names + 266, 22}, 262 },
  { {LoginCmdID_names + 288, 23}, 258 },
  { {LoginCmdID_names + 311, 25}, 269 },
  { {LoginCmdID_names + 336, 31}, 271 },
  { {LoginCmdID_names + 367, 23}, 260 },
};

static const int LoginCmdID_entries_by_number[] = {
  1, // 0 -> CID_LOGIN_REQ_DEFAULT
  5, // 257 -> CID_LOGIN_REQ_MSGSERVER
  12, // 258 -> CID_LOGIN_RES_MSGSERVER
  8, // 259 -> CID_LOGIN_REQ_USERLOGIN
  15, // 260 -> CID_LOGIN_RES_USERLOGIN
  4, // 261 -> CID_LOGIN_REQ_LOGINOUT
  11, // 262 -> CID_LOGIN_RES_LOGINOUT
  0, // 263 -> CID_LOGIN_KICK_USER
  2, // 264 -> CID_LOGIN_REQ_DEVICETOKEN
  9, // 265 -> CID_LOGIN_RES_DEVICETOKEN
  3, // 266 -> CID_LOGIN_REQ_KICKPCCLIENT
  10, // 267 -> CID_LOGIN_RES_KICKPCCLIENT
  6, // 268 -> CID_LOGIN_REQ_PUSH_SHIELD
  13, // 269 -> CID_LOGIN_RES_PUSH_SHIELD
  7, // 270 -> CID_LOGIN_REQ_QUERY_PUSH_SHIELD
  14, // 271 -> CID_LOGIN_RES_QUERY_PUSH_SHIELD
};

const std::string& LoginCmdID_Name(
    LoginCmdID value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          LoginCmdID_entries,
          LoginCmdID_entries_by_number,
          16, LoginCmdID_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      LoginCmdID_entries,
      LoginCmdID_entries_by_number,
      16, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     LoginCmdID_strings[idx].get();
}
bool LoginCmdID_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LoginCmdID* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      LoginCmdID_entries, 16, name, &int_value);
  if (success) {
    *value = static_cast<LoginCmdID>(int_value);
  }
  return success;
}
bool MessageCmdID_IsValid(int value) {
  switch (value) {
    case 0:
    case 769:
    case 770:
    case 771:
    case 772:
    case 773:
    case 774:
    case 775:
    case 776:
    case 777:
    case 778:
    case 779:
    case 780:
    case 781:
    case 782:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> MessageCmdID_strings[15] = {};

static const char MessageCmdID_names[] =
  "CID_MSG_DATA"
  "CID_MSG_DATA_ACK"
  "CID_MSG_DEFAULT"
  "CID_MSG_GET_BY_MSG_ID_REQ"
  "CID_MSG_GET_BY_MSG_ID_RES"
  "CID_MSG_GET_LATEST_MSG_ID_REQ"
  "CID_MSG_GET_LATEST_MSG_ID_RSP"
  "CID_MSG_LIST_REQUEST"
  "CID_MSG_LIST_RESPONSE"
  "CID_MSG_READ_ACK"
  "CID_MSG_READ_NOTIFY"
  "CID_MSG_TIME_REQUEST"
  "CID_MSG_TIME_RESPONSE"
  "CID_MSG_UNREAD_CNT_REQUEST"
  "CID_MSG_UNREAD_CNT_RESPONSE";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry MessageCmdID_entries[] = {
  { {MessageCmdID_names + 0, 12}, 769 },
  { {MessageCmdID_names + 12, 16}, 770 },
  { {MessageCmdID_names + 28, 15}, 0 },
  { {MessageCmdID_names + 43, 25}, 781 },
  { {MessageCmdID_names + 68, 25}, 782 },
  { {MessageCmdID_names + 93, 29}, 779 },
  { {MessageCmdID_names + 122, 29}, 780 },
  { {MessageCmdID_names + 151, 20}, 777 },
  { {MessageCmdID_names + 171, 21}, 778 },
  { {MessageCmdID_names + 192, 16}, 771 },
  { {MessageCmdID_names + 208, 19}, 772 },
  { {MessageCmdID_names + 227, 20}, 773 },
  { {MessageCmdID_names + 247, 21}, 774 },
  { {MessageCmdID_names + 268, 26}, 775 },
  { {MessageCmdID_names + 294, 27}, 776 },
};

static const int MessageCmdID_entries_by_number[] = {
  2, // 0 -> CID_MSG_DEFAULT
  0, // 769 -> CID_MSG_DATA
  1, // 770 -> CID_MSG_DATA_ACK
  9, // 771 -> CID_MSG_READ_ACK
  10, // 772 -> CID_MSG_READ_NOTIFY
  11, // 773 -> CID_MSG_TIME_REQUEST
  12, // 774 -> CID_MSG_TIME_RESPONSE
  13, // 775 -> CID_MSG_UNREAD_CNT_REQUEST
  14, // 776 -> CID_MSG_UNREAD_CNT_RESPONSE
  7, // 777 -> CID_MSG_LIST_REQUEST
  8, // 778 -> CID_MSG_LIST_RESPONSE
  5, // 779 -> CID_MSG_GET_LATEST_MSG_ID_REQ
  6, // 780 -> CID_MSG_GET_LATEST_MSG_ID_RSP
  3, // 781 -> CID_MSG_GET_BY_MSG_ID_REQ
  4, // 782 -> CID_MSG_GET_BY_MSG_ID_RES
};

const std::string& MessageCmdID_Name(
    MessageCmdID value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          MessageCmdID_entries,
          MessageCmdID_entries_by_number,
          15, MessageCmdID_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      MessageCmdID_entries,
      MessageCmdID_entries_by_number,
      15, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     MessageCmdID_strings[idx].get();
}
bool MessageCmdID_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MessageCmdID* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      MessageCmdID_entries, 15, name, &int_value);
  if (success) {
    *value = static_cast<MessageCmdID>(int_value);
  }
  return success;
}
bool UserStatType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> UserStatType_strings[4] = {};

static const char UserStatType_names[] =
  "USER_STATUS_DEFAULT"
  "USER_STATUS_LEAVE"
  "USER_STATUS_OFFLINE"
  "USER_STATUS_ONLINE";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry UserStatType_entries[] = {
  { {UserStatType_names + 0, 19}, 0 },
  { {UserStatType_names + 19, 17}, 3 },
  { {UserStatType_names + 36, 19}, 2 },
  { {UserStatType_names + 55, 18}, 1 },
};

static const int UserStatType_entries_by_number[] = {
  0, // 0 -> USER_STATUS_DEFAULT
  3, // 1 -> USER_STATUS_ONLINE
  2, // 2 -> USER_STATUS_OFFLINE
  1, // 3 -> USER_STATUS_LEAVE
};

const std::string& UserStatType_Name(
    UserStatType value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          UserStatType_entries,
          UserStatType_entries_by_number,
          4, UserStatType_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      UserStatType_entries,
      UserStatType_entries_by_number,
      4, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     UserStatType_strings[idx].get();
}
bool UserStatType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, UserStatType* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      UserStatType_entries, 4, name, &int_value);
  if (success) {
    *value = static_cast<UserStatType>(int_value);
  }
  return success;
}
bool ClientType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 17:
    case 18:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> ClientType_strings[5] = {};

static const char ClientType_names[] =
  "CLIENT_TYPE_ANDROID"
  "CLIENT_TYPE_DEFAULT"
  "CLIENT_TYPE_IOS"
  "CLIENT_TYPE_MAC"
  "CLIENT_TYPE_WINDOWS";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry ClientType_entries[] = {
  { {ClientType_names + 0, 19}, 18 },
  { {ClientType_names + 19, 19}, 0 },
  { {ClientType_names + 38, 15}, 17 },
  { {ClientType_names + 53, 15}, 2 },
  { {ClientType_names + 68, 19}, 1 },
};

static const int ClientType_entries_by_number[] = {
  1, // 0 -> CLIENT_TYPE_DEFAULT
  4, // 1 -> CLIENT_TYPE_WINDOWS
  3, // 2 -> CLIENT_TYPE_MAC
  2, // 17 -> CLIENT_TYPE_IOS
  0, // 18 -> CLIENT_TYPE_ANDROID
};

const std::string& ClientType_Name(
    ClientType value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          ClientType_entries,
          ClientType_entries_by_number,
          5, ClientType_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      ClientType_entries,
      ClientType_entries_by_number,
      5, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     ClientType_strings[idx].get();
}
bool ClientType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ClientType* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      ClientType_entries, 5, name, &int_value);
  if (success) {
    *value = static_cast<ClientType>(int_value);
  }
  return success;
}
bool MsgType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 17:
    case 18:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> MsgType_strings[5] = {};

static const char MsgType_names[] =
  "MSG_TYPE_DEFAULT"
  "MSG_TYPE_GROUP_AUDIO"
  "MSG_TYPE_GROUP_TEXT"
  "MSG_TYPE_SINGLE_AUDIO"
  "MSG_TYPE_SINGLE_TEXT";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry MsgType_entries[] = {
  { {MsgType_names + 0, 16}, 0 },
  { {MsgType_names + 16, 20}, 18 },
  { {MsgType_names + 36, 19}, 17 },
  { {MsgType_names + 55, 21}, 2 },
  { {MsgType_names + 76, 20}, 1 },
};

static const int MsgType_entries_by_number[] = {
  0, // 0 -> MSG_TYPE_DEFAULT
  4, // 1 -> MSG_TYPE_SINGLE_TEXT
  3, // 2 -> MSG_TYPE_SINGLE_AUDIO
  2, // 17 -> MSG_TYPE_GROUP_TEXT
  1, // 18 -> MSG_TYPE_GROUP_AUDIO
};

const std::string& MsgType_Name(
    MsgType value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          MsgType_entries,
          MsgType_entries_by_number,
          5, MsgType_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      MsgType_entries,
      MsgType_entries_by_number,
      5, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     MsgType_strings[idx].get();
}
bool MsgType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MsgType* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      MsgType_entries, 5, name, &int_value);
  if (success) {
    *value = static_cast<MsgType>(int_value);
  }
  return success;
}
bool SessionType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> SessionType_strings[3] = {};

static const char SessionType_names[] =
  "SESSION_TYPE_DEFAULT"
  "SESSION_TYPE_GROUP"
  "SESSION_TYPE_SINGLE";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry SessionType_entries[] = {
  { {SessionType_names + 0, 20}, 0 },
  { {SessionType_names + 20, 18}, 2 },
  { {SessionType_names + 38, 19}, 1 },
};

static const int SessionType_entries_by_number[] = {
  0, // 0 -> SESSION_TYPE_DEFAULT
  2, // 1 -> SESSION_TYPE_SINGLE
  1, // 2 -> SESSION_TYPE_GROUP
};

const std::string& SessionType_Name(
    SessionType value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          SessionType_entries,
          SessionType_entries_by_number,
          3, SessionType_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      SessionType_entries,
      SessionType_entries_by_number,
      3, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     SessionType_strings[idx].get();
}
bool SessionType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SessionType* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      SessionType_entries, 3, name, &int_value);
  if (success) {
    *value = static_cast<SessionType>(int_value);
  }
  return success;
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace BaseDefine
}  // namespace IM
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
