// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Login.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_IM_2eLogin_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_IM_2eLogin_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "IM.BaseDefine.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_IM_2eLogin_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_IM_2eLogin_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
namespace IM {
namespace Login {
class ArticleResponse;
struct ArticleResponseDefaultTypeInternal;
extern ArticleResponseDefaultTypeInternal _ArticleResponse_default_instance_;
class IMLoginReq;
struct IMLoginReqDefaultTypeInternal;
extern IMLoginReqDefaultTypeInternal _IMLoginReq_default_instance_;
class MusicResponse;
struct MusicResponseDefaultTypeInternal;
extern MusicResponseDefaultTypeInternal _MusicResponse_default_instance_;
}  // namespace Login
}  // namespace IM
PROTOBUF_NAMESPACE_OPEN
template<> ::IM::Login::ArticleResponse* Arena::CreateMaybeMessage<::IM::Login::ArticleResponse>(Arena*);
template<> ::IM::Login::IMLoginReq* Arena::CreateMaybeMessage<::IM::Login::IMLoginReq>(Arena*);
template<> ::IM::Login::MusicResponse* Arena::CreateMaybeMessage<::IM::Login::MusicResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace IM {
namespace Login {

// ===================================================================

class IMLoginReq final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:IM.Login.IMLoginReq) */ {
 public:
  inline IMLoginReq() : IMLoginReq(nullptr) {}
  ~IMLoginReq() override;
  explicit constexpr IMLoginReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IMLoginReq(const IMLoginReq& from);
  IMLoginReq(IMLoginReq&& from) noexcept
    : IMLoginReq() {
    *this = ::std::move(from);
  }

  inline IMLoginReq& operator=(const IMLoginReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline IMLoginReq& operator=(IMLoginReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const IMLoginReq& default_instance() {
    return *internal_default_instance();
  }
  enum TestUnionCase {
    kInt321 = 7,
    kString2 = 8,
    TEST_UNION_NOT_SET = 0,
  };

  enum PayloadCase {
    kArticleResponse = 9,
    kMusicResponse = 10,
    PAYLOAD_NOT_SET = 0,
  };

  static inline const IMLoginReq* internal_default_instance() {
    return reinterpret_cast<const IMLoginReq*>(
               &_IMLoginReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(IMLoginReq& a, IMLoginReq& b) {
    a.Swap(&b);
  }
  inline void Swap(IMLoginReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IMLoginReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IMLoginReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IMLoginReq>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const IMLoginReq& from);
  void MergeFrom(const IMLoginReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(IMLoginReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "IM.Login.IMLoginReq";
  }
  protected:
  explicit IMLoginReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserNameFieldNumber = 1,
    kPasswordFieldNumber = 2,
    kClientVersionFieldNumber = 5,
    kClientXxxFieldNumber = 6,
    kOnlineStatusFieldNumber = 3,
    kClientTypeFieldNumber = 4,
    kInt321FieldNumber = 7,
    kString2FieldNumber = 8,
    kArticleResponseFieldNumber = 9,
    kMusicResponseFieldNumber = 10,
  };
  // string user_name = 1;
  void clear_user_name();
  const std::string& user_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user_name();
  PROTOBUF_NODISCARD std::string* release_user_name();
  void set_allocated_user_name(std::string* user_name);
  private:
  const std::string& _internal_user_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_name(const std::string& value);
  std::string* _internal_mutable_user_name();
  public:

  // string password = 2;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // string client_version = 5;
  void clear_client_version();
  const std::string& client_version() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_client_version(ArgT0&& arg0, ArgT... args);
  std::string* mutable_client_version();
  PROTOBUF_NODISCARD std::string* release_client_version();
  void set_allocated_client_version(std::string* client_version);
  private:
  const std::string& _internal_client_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_client_version(const std::string& value);
  std::string* _internal_mutable_client_version();
  public:

  // string client_xxx = 6;
  void clear_client_xxx();
  const std::string& client_xxx() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_client_xxx(ArgT0&& arg0, ArgT... args);
  std::string* mutable_client_xxx();
  PROTOBUF_NODISCARD std::string* release_client_xxx();
  void set_allocated_client_xxx(std::string* client_xxx);
  private:
  const std::string& _internal_client_xxx() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_client_xxx(const std::string& value);
  std::string* _internal_mutable_client_xxx();
  public:

  // .IM.BaseDefine.UserStatType online_status = 3;
  void clear_online_status();
  ::IM::BaseDefine::UserStatType online_status() const;
  void set_online_status(::IM::BaseDefine::UserStatType value);
  private:
  ::IM::BaseDefine::UserStatType _internal_online_status() const;
  void _internal_set_online_status(::IM::BaseDefine::UserStatType value);
  public:

  // .IM.BaseDefine.ClientType client_type = 4;
  void clear_client_type();
  ::IM::BaseDefine::ClientType client_type() const;
  void set_client_type(::IM::BaseDefine::ClientType value);
  private:
  ::IM::BaseDefine::ClientType _internal_client_type() const;
  void _internal_set_client_type(::IM::BaseDefine::ClientType value);
  public:

  // int32 int32_1 = 7;
  bool has_int32_1() const;
  private:
  bool _internal_has_int32_1() const;
  public:
  void clear_int32_1();
  int32_t int32_1() const;
  void set_int32_1(int32_t value);
  private:
  int32_t _internal_int32_1() const;
  void _internal_set_int32_1(int32_t value);
  public:

  // string string_2 = 8;
  bool has_string_2() const;
  private:
  bool _internal_has_string_2() const;
  public:
  void clear_string_2();
  const std::string& string_2() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_string_2(ArgT0&& arg0, ArgT... args);
  std::string* mutable_string_2();
  PROTOBUF_NODISCARD std::string* release_string_2();
  void set_allocated_string_2(std::string* string_2);
  private:
  const std::string& _internal_string_2() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_string_2(const std::string& value);
  std::string* _internal_mutable_string_2();
  public:

  // .IM.Login.ArticleResponse articleResponse = 9;
  bool has_articleresponse() const;
  private:
  bool _internal_has_articleresponse() const;
  public:
  void clear_articleresponse();
  const ::IM::Login::ArticleResponse& articleresponse() const;
  PROTOBUF_NODISCARD ::IM::Login::ArticleResponse* release_articleresponse();
  ::IM::Login::ArticleResponse* mutable_articleresponse();
  void set_allocated_articleresponse(::IM::Login::ArticleResponse* articleresponse);
  private:
  const ::IM::Login::ArticleResponse& _internal_articleresponse() const;
  ::IM::Login::ArticleResponse* _internal_mutable_articleresponse();
  public:
  void unsafe_arena_set_allocated_articleresponse(
      ::IM::Login::ArticleResponse* articleresponse);
  ::IM::Login::ArticleResponse* unsafe_arena_release_articleresponse();

  // .IM.Login.MusicResponse musicResponse = 10;
  bool has_musicresponse() const;
  private:
  bool _internal_has_musicresponse() const;
  public:
  void clear_musicresponse();
  const ::IM::Login::MusicResponse& musicresponse() const;
  PROTOBUF_NODISCARD ::IM::Login::MusicResponse* release_musicresponse();
  ::IM::Login::MusicResponse* mutable_musicresponse();
  void set_allocated_musicresponse(::IM::Login::MusicResponse* musicresponse);
  private:
  const ::IM::Login::MusicResponse& _internal_musicresponse() const;
  ::IM::Login::MusicResponse* _internal_mutable_musicresponse();
  public:
  void unsafe_arena_set_allocated_musicresponse(
      ::IM::Login::MusicResponse* musicresponse);
  ::IM::Login::MusicResponse* unsafe_arena_release_musicresponse();

  void clear_test_union();
  TestUnionCase test_union_case() const;
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:IM.Login.IMLoginReq)
 private:
  class _Internal;
  void set_has_int32_1();
  void set_has_string_2();
  void set_has_articleresponse();
  void set_has_musicresponse();

  inline bool has_test_union() const;
  inline void clear_has_test_union();

  inline bool has_payload() const;
  inline void clear_has_payload();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr client_version_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr client_xxx_;
  int online_status_;
  int client_type_;
  union TestUnionUnion {
    constexpr TestUnionUnion() : _constinit_{} {}
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
    int32_t int32_1_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr string_2_;
  } test_union_;
  union PayloadUnion {
    constexpr PayloadUnion() : _constinit_{} {}
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
    ::IM::Login::ArticleResponse* articleresponse_;
    ::IM::Login::MusicResponse* musicresponse_;
  } payload_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  uint32_t _oneof_case_[2];

  friend struct ::TableStruct_IM_2eLogin_2eproto;
};
// -------------------------------------------------------------------

class ArticleResponse final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:IM.Login.ArticleResponse) */ {
 public:
  inline ArticleResponse() : ArticleResponse(nullptr) {}
  ~ArticleResponse() override;
  explicit constexpr ArticleResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ArticleResponse(const ArticleResponse& from);
  ArticleResponse(ArticleResponse&& from) noexcept
    : ArticleResponse() {
    *this = ::std::move(from);
  }

  inline ArticleResponse& operator=(const ArticleResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ArticleResponse& operator=(ArticleResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ArticleResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ArticleResponse* internal_default_instance() {
    return reinterpret_cast<const ArticleResponse*>(
               &_ArticleResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ArticleResponse& a, ArticleResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ArticleResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ArticleResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ArticleResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ArticleResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const ArticleResponse& from);
  void MergeFrom(const ArticleResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ArticleResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "IM.Login.ArticleResponse";
  }
  protected:
  explicit ArticleResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTitleFieldNumber = 1,
    kAuthorFieldNumber = 2,
    kDateFieldNumber = 3,
  };
  // string title = 1;
  void clear_title();
  const std::string& title() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_title(ArgT0&& arg0, ArgT... args);
  std::string* mutable_title();
  PROTOBUF_NODISCARD std::string* release_title();
  void set_allocated_title(std::string* title);
  private:
  const std::string& _internal_title() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_title(const std::string& value);
  std::string* _internal_mutable_title();
  public:

  // string author = 2;
  void clear_author();
  const std::string& author() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_author(ArgT0&& arg0, ArgT... args);
  std::string* mutable_author();
  PROTOBUF_NODISCARD std::string* release_author();
  void set_allocated_author(std::string* author);
  private:
  const std::string& _internal_author() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_author(const std::string& value);
  std::string* _internal_mutable_author();
  public:

  // string date = 3;
  void clear_date();
  const std::string& date() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_date(ArgT0&& arg0, ArgT... args);
  std::string* mutable_date();
  PROTOBUF_NODISCARD std::string* release_date();
  void set_allocated_date(std::string* date);
  private:
  const std::string& _internal_date() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_date(const std::string& value);
  std::string* _internal_mutable_date();
  public:

  // @@protoc_insertion_point(class_scope:IM.Login.ArticleResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr title_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr author_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr date_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_IM_2eLogin_2eproto;
};
// -------------------------------------------------------------------

class MusicResponse final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:IM.Login.MusicResponse) */ {
 public:
  inline MusicResponse() : MusicResponse(nullptr) {}
  ~MusicResponse() override;
  explicit constexpr MusicResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MusicResponse(const MusicResponse& from);
  MusicResponse(MusicResponse&& from) noexcept
    : MusicResponse() {
    *this = ::std::move(from);
  }

  inline MusicResponse& operator=(const MusicResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline MusicResponse& operator=(MusicResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const MusicResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const MusicResponse* internal_default_instance() {
    return reinterpret_cast<const MusicResponse*>(
               &_MusicResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MusicResponse& a, MusicResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(MusicResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MusicResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MusicResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MusicResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const MusicResponse& from);
  void MergeFrom(const MusicResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MusicResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "IM.Login.MusicResponse";
  }
  protected:
  explicit MusicResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTitleFieldNumber = 1,
    kAuthorFieldNumber = 2,
    kDataFieldNumber = 3,
  };
  // string title = 1;
  void clear_title();
  const std::string& title() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_title(ArgT0&& arg0, ArgT... args);
  std::string* mutable_title();
  PROTOBUF_NODISCARD std::string* release_title();
  void set_allocated_title(std::string* title);
  private:
  const std::string& _internal_title() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_title(const std::string& value);
  std::string* _internal_mutable_title();
  public:

  // string author = 2;
  void clear_author();
  const std::string& author() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_author(ArgT0&& arg0, ArgT... args);
  std::string* mutable_author();
  PROTOBUF_NODISCARD std::string* release_author();
  void set_allocated_author(std::string* author);
  private:
  const std::string& _internal_author() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_author(const std::string& value);
  std::string* _internal_mutable_author();
  public:

  // bytes data = 3;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // @@protoc_insertion_point(class_scope:IM.Login.MusicResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr title_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr author_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_IM_2eLogin_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IMLoginReq

// string user_name = 1;
inline void IMLoginReq::clear_user_name() {
  user_name_.ClearToEmpty();
}
inline const std::string& IMLoginReq::user_name() const {
  // @@protoc_insertion_point(field_get:IM.Login.IMLoginReq.user_name)
  return _internal_user_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IMLoginReq::set_user_name(ArgT0&& arg0, ArgT... args) {
 
 user_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:IM.Login.IMLoginReq.user_name)
}
inline std::string* IMLoginReq::mutable_user_name() {
  std::string* _s = _internal_mutable_user_name();
  // @@protoc_insertion_point(field_mutable:IM.Login.IMLoginReq.user_name)
  return _s;
}
inline const std::string& IMLoginReq::_internal_user_name() const {
  return user_name_.Get();
}
inline void IMLoginReq::_internal_set_user_name(const std::string& value) {
  
  user_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* IMLoginReq::_internal_mutable_user_name() {
  
  return user_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* IMLoginReq::release_user_name() {
  // @@protoc_insertion_point(field_release:IM.Login.IMLoginReq.user_name)
  return user_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void IMLoginReq::set_allocated_user_name(std::string* user_name) {
  if (user_name != nullptr) {
    
  } else {
    
  }
  user_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), user_name,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (user_name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    user_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:IM.Login.IMLoginReq.user_name)
}

// string password = 2;
inline void IMLoginReq::clear_password() {
  password_.ClearToEmpty();
}
inline const std::string& IMLoginReq::password() const {
  // @@protoc_insertion_point(field_get:IM.Login.IMLoginReq.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IMLoginReq::set_password(ArgT0&& arg0, ArgT... args) {
 
 password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:IM.Login.IMLoginReq.password)
}
inline std::string* IMLoginReq::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:IM.Login.IMLoginReq.password)
  return _s;
}
inline const std::string& IMLoginReq::_internal_password() const {
  return password_.Get();
}
inline void IMLoginReq::_internal_set_password(const std::string& value) {
  
  password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* IMLoginReq::_internal_mutable_password() {
  
  return password_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* IMLoginReq::release_password() {
  // @@protoc_insertion_point(field_release:IM.Login.IMLoginReq.password)
  return password_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void IMLoginReq::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  password_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (password_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    password_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:IM.Login.IMLoginReq.password)
}

// .IM.BaseDefine.UserStatType online_status = 3;
inline void IMLoginReq::clear_online_status() {
  online_status_ = 0;
}
inline ::IM::BaseDefine::UserStatType IMLoginReq::_internal_online_status() const {
  return static_cast< ::IM::BaseDefine::UserStatType >(online_status_);
}
inline ::IM::BaseDefine::UserStatType IMLoginReq::online_status() const {
  // @@protoc_insertion_point(field_get:IM.Login.IMLoginReq.online_status)
  return _internal_online_status();
}
inline void IMLoginReq::_internal_set_online_status(::IM::BaseDefine::UserStatType value) {
  
  online_status_ = value;
}
inline void IMLoginReq::set_online_status(::IM::BaseDefine::UserStatType value) {
  _internal_set_online_status(value);
  // @@protoc_insertion_point(field_set:IM.Login.IMLoginReq.online_status)
}

// .IM.BaseDefine.ClientType client_type = 4;
inline void IMLoginReq::clear_client_type() {
  client_type_ = 0;
}
inline ::IM::BaseDefine::ClientType IMLoginReq::_internal_client_type() const {
  return static_cast< ::IM::BaseDefine::ClientType >(client_type_);
}
inline ::IM::BaseDefine::ClientType IMLoginReq::client_type() const {
  // @@protoc_insertion_point(field_get:IM.Login.IMLoginReq.client_type)
  return _internal_client_type();
}
inline void IMLoginReq::_internal_set_client_type(::IM::BaseDefine::ClientType value) {
  
  client_type_ = value;
}
inline void IMLoginReq::set_client_type(::IM::BaseDefine::ClientType value) {
  _internal_set_client_type(value);
  // @@protoc_insertion_point(field_set:IM.Login.IMLoginReq.client_type)
}

// string client_version = 5;
inline void IMLoginReq::clear_client_version() {
  client_version_.ClearToEmpty();
}
inline const std::string& IMLoginReq::client_version() const {
  // @@protoc_insertion_point(field_get:IM.Login.IMLoginReq.client_version)
  return _internal_client_version();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IMLoginReq::set_client_version(ArgT0&& arg0, ArgT... args) {
 
 client_version_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:IM.Login.IMLoginReq.client_version)
}
inline std::string* IMLoginReq::mutable_client_version() {
  std::string* _s = _internal_mutable_client_version();
  // @@protoc_insertion_point(field_mutable:IM.Login.IMLoginReq.client_version)
  return _s;
}
inline const std::string& IMLoginReq::_internal_client_version() const {
  return client_version_.Get();
}
inline void IMLoginReq::_internal_set_client_version(const std::string& value) {
  
  client_version_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* IMLoginReq::_internal_mutable_client_version() {
  
  return client_version_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* IMLoginReq::release_client_version() {
  // @@protoc_insertion_point(field_release:IM.Login.IMLoginReq.client_version)
  return client_version_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void IMLoginReq::set_allocated_client_version(std::string* client_version) {
  if (client_version != nullptr) {
    
  } else {
    
  }
  client_version_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), client_version,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (client_version_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    client_version_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:IM.Login.IMLoginReq.client_version)
}

// string client_xxx = 6;
inline void IMLoginReq::clear_client_xxx() {
  client_xxx_.ClearToEmpty();
}
inline const std::string& IMLoginReq::client_xxx() const {
  // @@protoc_insertion_point(field_get:IM.Login.IMLoginReq.client_xxx)
  return _internal_client_xxx();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IMLoginReq::set_client_xxx(ArgT0&& arg0, ArgT... args) {
 
 client_xxx_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:IM.Login.IMLoginReq.client_xxx)
}
inline std::string* IMLoginReq::mutable_client_xxx() {
  std::string* _s = _internal_mutable_client_xxx();
  // @@protoc_insertion_point(field_mutable:IM.Login.IMLoginReq.client_xxx)
  return _s;
}
inline const std::string& IMLoginReq::_internal_client_xxx() const {
  return client_xxx_.Get();
}
inline void IMLoginReq::_internal_set_client_xxx(const std::string& value) {
  
  client_xxx_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* IMLoginReq::_internal_mutable_client_xxx() {
  
  return client_xxx_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* IMLoginReq::release_client_xxx() {
  // @@protoc_insertion_point(field_release:IM.Login.IMLoginReq.client_xxx)
  return client_xxx_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void IMLoginReq::set_allocated_client_xxx(std::string* client_xxx) {
  if (client_xxx != nullptr) {
    
  } else {
    
  }
  client_xxx_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), client_xxx,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (client_xxx_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    client_xxx_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:IM.Login.IMLoginReq.client_xxx)
}

// int32 int32_1 = 7;
inline bool IMLoginReq::_internal_has_int32_1() const {
  return test_union_case() == kInt321;
}
inline bool IMLoginReq::has_int32_1() const {
  return _internal_has_int32_1();
}
inline void IMLoginReq::set_has_int32_1() {
  _oneof_case_[0] = kInt321;
}
inline void IMLoginReq::clear_int32_1() {
  if (_internal_has_int32_1()) {
    test_union_.int32_1_ = 0;
    clear_has_test_union();
  }
}
inline int32_t IMLoginReq::_internal_int32_1() const {
  if (_internal_has_int32_1()) {
    return test_union_.int32_1_;
  }
  return 0;
}
inline void IMLoginReq::_internal_set_int32_1(int32_t value) {
  if (!_internal_has_int32_1()) {
    clear_test_union();
    set_has_int32_1();
  }
  test_union_.int32_1_ = value;
}
inline int32_t IMLoginReq::int32_1() const {
  // @@protoc_insertion_point(field_get:IM.Login.IMLoginReq.int32_1)
  return _internal_int32_1();
}
inline void IMLoginReq::set_int32_1(int32_t value) {
  _internal_set_int32_1(value);
  // @@protoc_insertion_point(field_set:IM.Login.IMLoginReq.int32_1)
}

// string string_2 = 8;
inline bool IMLoginReq::_internal_has_string_2() const {
  return test_union_case() == kString2;
}
inline bool IMLoginReq::has_string_2() const {
  return _internal_has_string_2();
}
inline void IMLoginReq::set_has_string_2() {
  _oneof_case_[0] = kString2;
}
inline void IMLoginReq::clear_string_2() {
  if (_internal_has_string_2()) {
    test_union_.string_2_.Destroy(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
    clear_has_test_union();
  }
}
inline const std::string& IMLoginReq::string_2() const {
  // @@protoc_insertion_point(field_get:IM.Login.IMLoginReq.string_2)
  return _internal_string_2();
}
template <typename ArgT0, typename... ArgT>
inline void IMLoginReq::set_string_2(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_string_2()) {
    clear_test_union();
    set_has_string_2();
    test_union_.string_2_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  test_union_.string_2_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:IM.Login.IMLoginReq.string_2)
}
inline std::string* IMLoginReq::mutable_string_2() {
  std::string* _s = _internal_mutable_string_2();
  // @@protoc_insertion_point(field_mutable:IM.Login.IMLoginReq.string_2)
  return _s;
}
inline const std::string& IMLoginReq::_internal_string_2() const {
  if (_internal_has_string_2()) {
    return test_union_.string_2_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void IMLoginReq::_internal_set_string_2(const std::string& value) {
  if (!_internal_has_string_2()) {
    clear_test_union();
    set_has_string_2();
    test_union_.string_2_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  test_union_.string_2_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* IMLoginReq::_internal_mutable_string_2() {
  if (!_internal_has_string_2()) {
    clear_test_union();
    set_has_string_2();
    test_union_.string_2_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  return test_union_.string_2_.Mutable(
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* IMLoginReq::release_string_2() {
  // @@protoc_insertion_point(field_release:IM.Login.IMLoginReq.string_2)
  if (_internal_has_string_2()) {
    clear_has_test_union();
    return test_union_.string_2_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
  } else {
    return nullptr;
  }
}
inline void IMLoginReq::set_allocated_string_2(std::string* string_2) {
  if (has_test_union()) {
    clear_test_union();
  }
  if (string_2 != nullptr) {
    set_has_string_2();
    test_union_.string_2_.UnsafeSetDefault(string_2);
    ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArenaForAllocation();
    if (arena != nullptr) {
      arena->Own(string_2);
    }
  }
  // @@protoc_insertion_point(field_set_allocated:IM.Login.IMLoginReq.string_2)
}

// .IM.Login.ArticleResponse articleResponse = 9;
inline bool IMLoginReq::_internal_has_articleresponse() const {
  return payload_case() == kArticleResponse;
}
inline bool IMLoginReq::has_articleresponse() const {
  return _internal_has_articleresponse();
}
inline void IMLoginReq::set_has_articleresponse() {
  _oneof_case_[1] = kArticleResponse;
}
inline void IMLoginReq::clear_articleresponse() {
  if (_internal_has_articleresponse()) {
    if (GetArenaForAllocation() == nullptr) {
      delete payload_.articleresponse_;
    }
    clear_has_payload();
  }
}
inline ::IM::Login::ArticleResponse* IMLoginReq::release_articleresponse() {
  // @@protoc_insertion_point(field_release:IM.Login.IMLoginReq.articleResponse)
  if (_internal_has_articleresponse()) {
    clear_has_payload();
      ::IM::Login::ArticleResponse* temp = payload_.articleresponse_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    payload_.articleresponse_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::IM::Login::ArticleResponse& IMLoginReq::_internal_articleresponse() const {
  return _internal_has_articleresponse()
      ? *payload_.articleresponse_
      : reinterpret_cast< ::IM::Login::ArticleResponse&>(::IM::Login::_ArticleResponse_default_instance_);
}
inline const ::IM::Login::ArticleResponse& IMLoginReq::articleresponse() const {
  // @@protoc_insertion_point(field_get:IM.Login.IMLoginReq.articleResponse)
  return _internal_articleresponse();
}
inline ::IM::Login::ArticleResponse* IMLoginReq::unsafe_arena_release_articleresponse() {
  // @@protoc_insertion_point(field_unsafe_arena_release:IM.Login.IMLoginReq.articleResponse)
  if (_internal_has_articleresponse()) {
    clear_has_payload();
    ::IM::Login::ArticleResponse* temp = payload_.articleresponse_;
    payload_.articleresponse_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void IMLoginReq::unsafe_arena_set_allocated_articleresponse(::IM::Login::ArticleResponse* articleresponse) {
  clear_payload();
  if (articleresponse) {
    set_has_articleresponse();
    payload_.articleresponse_ = articleresponse;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:IM.Login.IMLoginReq.articleResponse)
}
inline ::IM::Login::ArticleResponse* IMLoginReq::_internal_mutable_articleresponse() {
  if (!_internal_has_articleresponse()) {
    clear_payload();
    set_has_articleresponse();
    payload_.articleresponse_ = CreateMaybeMessage< ::IM::Login::ArticleResponse >(GetArenaForAllocation());
  }
  return payload_.articleresponse_;
}
inline ::IM::Login::ArticleResponse* IMLoginReq::mutable_articleresponse() {
  ::IM::Login::ArticleResponse* _msg = _internal_mutable_articleresponse();
  // @@protoc_insertion_point(field_mutable:IM.Login.IMLoginReq.articleResponse)
  return _msg;
}

// .IM.Login.MusicResponse musicResponse = 10;
inline bool IMLoginReq::_internal_has_musicresponse() const {
  return payload_case() == kMusicResponse;
}
inline bool IMLoginReq::has_musicresponse() const {
  return _internal_has_musicresponse();
}
inline void IMLoginReq::set_has_musicresponse() {
  _oneof_case_[1] = kMusicResponse;
}
inline void IMLoginReq::clear_musicresponse() {
  if (_internal_has_musicresponse()) {
    if (GetArenaForAllocation() == nullptr) {
      delete payload_.musicresponse_;
    }
    clear_has_payload();
  }
}
inline ::IM::Login::MusicResponse* IMLoginReq::release_musicresponse() {
  // @@protoc_insertion_point(field_release:IM.Login.IMLoginReq.musicResponse)
  if (_internal_has_musicresponse()) {
    clear_has_payload();
      ::IM::Login::MusicResponse* temp = payload_.musicresponse_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    payload_.musicresponse_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::IM::Login::MusicResponse& IMLoginReq::_internal_musicresponse() const {
  return _internal_has_musicresponse()
      ? *payload_.musicresponse_
      : reinterpret_cast< ::IM::Login::MusicResponse&>(::IM::Login::_MusicResponse_default_instance_);
}
inline const ::IM::Login::MusicResponse& IMLoginReq::musicresponse() const {
  // @@protoc_insertion_point(field_get:IM.Login.IMLoginReq.musicResponse)
  return _internal_musicresponse();
}
inline ::IM::Login::MusicResponse* IMLoginReq::unsafe_arena_release_musicresponse() {
  // @@protoc_insertion_point(field_unsafe_arena_release:IM.Login.IMLoginReq.musicResponse)
  if (_internal_has_musicresponse()) {
    clear_has_payload();
    ::IM::Login::MusicResponse* temp = payload_.musicresponse_;
    payload_.musicresponse_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void IMLoginReq::unsafe_arena_set_allocated_musicresponse(::IM::Login::MusicResponse* musicresponse) {
  clear_payload();
  if (musicresponse) {
    set_has_musicresponse();
    payload_.musicresponse_ = musicresponse;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:IM.Login.IMLoginReq.musicResponse)
}
inline ::IM::Login::MusicResponse* IMLoginReq::_internal_mutable_musicresponse() {
  if (!_internal_has_musicresponse()) {
    clear_payload();
    set_has_musicresponse();
    payload_.musicresponse_ = CreateMaybeMessage< ::IM::Login::MusicResponse >(GetArenaForAllocation());
  }
  return payload_.musicresponse_;
}
inline ::IM::Login::MusicResponse* IMLoginReq::mutable_musicresponse() {
  ::IM::Login::MusicResponse* _msg = _internal_mutable_musicresponse();
  // @@protoc_insertion_point(field_mutable:IM.Login.IMLoginReq.musicResponse)
  return _msg;
}

inline bool IMLoginReq::has_test_union() const {
  return test_union_case() != TEST_UNION_NOT_SET;
}
inline void IMLoginReq::clear_has_test_union() {
  _oneof_case_[0] = TEST_UNION_NOT_SET;
}
inline bool IMLoginReq::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void IMLoginReq::clear_has_payload() {
  _oneof_case_[1] = PAYLOAD_NOT_SET;
}
inline IMLoginReq::TestUnionCase IMLoginReq::test_union_case() const {
  return IMLoginReq::TestUnionCase(_oneof_case_[0]);
}
inline IMLoginReq::PayloadCase IMLoginReq::payload_case() const {
  return IMLoginReq::PayloadCase(_oneof_case_[1]);
}
// -------------------------------------------------------------------

// ArticleResponse

// string title = 1;
inline void ArticleResponse::clear_title() {
  title_.ClearToEmpty();
}
inline const std::string& ArticleResponse::title() const {
  // @@protoc_insertion_point(field_get:IM.Login.ArticleResponse.title)
  return _internal_title();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ArticleResponse::set_title(ArgT0&& arg0, ArgT... args) {
 
 title_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:IM.Login.ArticleResponse.title)
}
inline std::string* ArticleResponse::mutable_title() {
  std::string* _s = _internal_mutable_title();
  // @@protoc_insertion_point(field_mutable:IM.Login.ArticleResponse.title)
  return _s;
}
inline const std::string& ArticleResponse::_internal_title() const {
  return title_.Get();
}
inline void ArticleResponse::_internal_set_title(const std::string& value) {
  
  title_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ArticleResponse::_internal_mutable_title() {
  
  return title_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ArticleResponse::release_title() {
  // @@protoc_insertion_point(field_release:IM.Login.ArticleResponse.title)
  return title_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ArticleResponse::set_allocated_title(std::string* title) {
  if (title != nullptr) {
    
  } else {
    
  }
  title_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), title,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (title_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    title_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:IM.Login.ArticleResponse.title)
}

// string author = 2;
inline void ArticleResponse::clear_author() {
  author_.ClearToEmpty();
}
inline const std::string& ArticleResponse::author() const {
  // @@protoc_insertion_point(field_get:IM.Login.ArticleResponse.author)
  return _internal_author();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ArticleResponse::set_author(ArgT0&& arg0, ArgT... args) {
 
 author_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:IM.Login.ArticleResponse.author)
}
inline std::string* ArticleResponse::mutable_author() {
  std::string* _s = _internal_mutable_author();
  // @@protoc_insertion_point(field_mutable:IM.Login.ArticleResponse.author)
  return _s;
}
inline const std::string& ArticleResponse::_internal_author() const {
  return author_.Get();
}
inline void ArticleResponse::_internal_set_author(const std::string& value) {
  
  author_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ArticleResponse::_internal_mutable_author() {
  
  return author_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ArticleResponse::release_author() {
  // @@protoc_insertion_point(field_release:IM.Login.ArticleResponse.author)
  return author_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ArticleResponse::set_allocated_author(std::string* author) {
  if (author != nullptr) {
    
  } else {
    
  }
  author_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), author,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (author_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    author_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:IM.Login.ArticleResponse.author)
}

// string date = 3;
inline void ArticleResponse::clear_date() {
  date_.ClearToEmpty();
}
inline const std::string& ArticleResponse::date() const {
  // @@protoc_insertion_point(field_get:IM.Login.ArticleResponse.date)
  return _internal_date();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ArticleResponse::set_date(ArgT0&& arg0, ArgT... args) {
 
 date_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:IM.Login.ArticleResponse.date)
}
inline std::string* ArticleResponse::mutable_date() {
  std::string* _s = _internal_mutable_date();
  // @@protoc_insertion_point(field_mutable:IM.Login.ArticleResponse.date)
  return _s;
}
inline const std::string& ArticleResponse::_internal_date() const {
  return date_.Get();
}
inline void ArticleResponse::_internal_set_date(const std::string& value) {
  
  date_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ArticleResponse::_internal_mutable_date() {
  
  return date_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ArticleResponse::release_date() {
  // @@protoc_insertion_point(field_release:IM.Login.ArticleResponse.date)
  return date_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ArticleResponse::set_allocated_date(std::string* date) {
  if (date != nullptr) {
    
  } else {
    
  }
  date_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), date,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (date_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    date_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:IM.Login.ArticleResponse.date)
}

// -------------------------------------------------------------------

// MusicResponse

// string title = 1;
inline void MusicResponse::clear_title() {
  title_.ClearToEmpty();
}
inline const std::string& MusicResponse::title() const {
  // @@protoc_insertion_point(field_get:IM.Login.MusicResponse.title)
  return _internal_title();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MusicResponse::set_title(ArgT0&& arg0, ArgT... args) {
 
 title_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:IM.Login.MusicResponse.title)
}
inline std::string* MusicResponse::mutable_title() {
  std::string* _s = _internal_mutable_title();
  // @@protoc_insertion_point(field_mutable:IM.Login.MusicResponse.title)
  return _s;
}
inline const std::string& MusicResponse::_internal_title() const {
  return title_.Get();
}
inline void MusicResponse::_internal_set_title(const std::string& value) {
  
  title_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* MusicResponse::_internal_mutable_title() {
  
  return title_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* MusicResponse::release_title() {
  // @@protoc_insertion_point(field_release:IM.Login.MusicResponse.title)
  return title_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void MusicResponse::set_allocated_title(std::string* title) {
  if (title != nullptr) {
    
  } else {
    
  }
  title_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), title,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (title_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    title_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:IM.Login.MusicResponse.title)
}

// string author = 2;
inline void MusicResponse::clear_author() {
  author_.ClearToEmpty();
}
inline const std::string& MusicResponse::author() const {
  // @@protoc_insertion_point(field_get:IM.Login.MusicResponse.author)
  return _internal_author();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MusicResponse::set_author(ArgT0&& arg0, ArgT... args) {
 
 author_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:IM.Login.MusicResponse.author)
}
inline std::string* MusicResponse::mutable_author() {
  std::string* _s = _internal_mutable_author();
  // @@protoc_insertion_point(field_mutable:IM.Login.MusicResponse.author)
  return _s;
}
inline const std::string& MusicResponse::_internal_author() const {
  return author_.Get();
}
inline void MusicResponse::_internal_set_author(const std::string& value) {
  
  author_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* MusicResponse::_internal_mutable_author() {
  
  return author_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* MusicResponse::release_author() {
  // @@protoc_insertion_point(field_release:IM.Login.MusicResponse.author)
  return author_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void MusicResponse::set_allocated_author(std::string* author) {
  if (author != nullptr) {
    
  } else {
    
  }
  author_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), author,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (author_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    author_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:IM.Login.MusicResponse.author)
}

// bytes data = 3;
inline void MusicResponse::clear_data() {
  data_.ClearToEmpty();
}
inline const std::string& MusicResponse::data() const {
  // @@protoc_insertion_point(field_get:IM.Login.MusicResponse.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MusicResponse::set_data(ArgT0&& arg0, ArgT... args) {
 
 data_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:IM.Login.MusicResponse.data)
}
inline std::string* MusicResponse::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:IM.Login.MusicResponse.data)
  return _s;
}
inline const std::string& MusicResponse::_internal_data() const {
  return data_.Get();
}
inline void MusicResponse::_internal_set_data(const std::string& value) {
  
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* MusicResponse::_internal_mutable_data() {
  
  return data_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* MusicResponse::release_data() {
  // @@protoc_insertion_point(field_release:IM.Login.MusicResponse.data)
  return data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void MusicResponse::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (data_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:IM.Login.MusicResponse.data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Login
}  // namespace IM

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_IM_2eLogin_2eproto
