// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_IM_2eMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_IM_2eMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "IM.BaseDefine.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_IM_2eMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_IM_2eMessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
namespace IM {
namespace Message {
class IMMsgData;
struct IMMsgDataDefaultTypeInternal;
extern IMMsgDataDefaultTypeInternal _IMMsgData_default_instance_;
class IMMsgDataAck;
struct IMMsgDataAckDefaultTypeInternal;
extern IMMsgDataAckDefaultTypeInternal _IMMsgDataAck_default_instance_;
}  // namespace Message
}  // namespace IM
PROTOBUF_NAMESPACE_OPEN
template<> ::IM::Message::IMMsgData* Arena::CreateMaybeMessage<::IM::Message::IMMsgData>(Arena*);
template<> ::IM::Message::IMMsgDataAck* Arena::CreateMaybeMessage<::IM::Message::IMMsgDataAck>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace IM {
namespace Message {

// ===================================================================

class IMMsgData final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:IM.Message.IMMsgData) */ {
 public:
  inline IMMsgData() : IMMsgData(nullptr) {}
  ~IMMsgData() override;
  explicit constexpr IMMsgData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IMMsgData(const IMMsgData& from);
  IMMsgData(IMMsgData&& from) noexcept
    : IMMsgData() {
    *this = ::std::move(from);
  }

  inline IMMsgData& operator=(const IMMsgData& from) {
    CopyFrom(from);
    return *this;
  }
  inline IMMsgData& operator=(IMMsgData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const IMMsgData& default_instance() {
    return *internal_default_instance();
  }
  static inline const IMMsgData* internal_default_instance() {
    return reinterpret_cast<const IMMsgData*>(
               &_IMMsgData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(IMMsgData& a, IMMsgData& b) {
    a.Swap(&b);
  }
  inline void Swap(IMMsgData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IMMsgData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IMMsgData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IMMsgData>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const IMMsgData& from);
  void MergeFrom(const IMMsgData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(IMMsgData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "IM.Message.IMMsgData";
  }
  protected:
  explicit IMMsgData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgDataFieldNumber = 6,
    kAttachDataFieldNumber = 20,
    kFromUserIdFieldNumber = 1,
    kToSessionIdFieldNumber = 2,
    kMsgIdFieldNumber = 3,
    kCreateTimeFieldNumber = 4,
    kMsgTypeFieldNumber = 5,
  };
  // bytes msg_data = 6;
  void clear_msg_data();
  const std::string& msg_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_msg_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_msg_data();
  PROTOBUF_NODISCARD std::string* release_msg_data();
  void set_allocated_msg_data(std::string* msg_data);
  private:
  const std::string& _internal_msg_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg_data(const std::string& value);
  std::string* _internal_mutable_msg_data();
  public:

  // bytes attach_data = 20;
  void clear_attach_data();
  const std::string& attach_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_attach_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_attach_data();
  PROTOBUF_NODISCARD std::string* release_attach_data();
  void set_allocated_attach_data(std::string* attach_data);
  private:
  const std::string& _internal_attach_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_attach_data(const std::string& value);
  std::string* _internal_mutable_attach_data();
  public:

  // uint32 from_user_id = 1;
  void clear_from_user_id();
  uint32_t from_user_id() const;
  void set_from_user_id(uint32_t value);
  private:
  uint32_t _internal_from_user_id() const;
  void _internal_set_from_user_id(uint32_t value);
  public:

  // uint32 to_session_id = 2;
  void clear_to_session_id();
  uint32_t to_session_id() const;
  void set_to_session_id(uint32_t value);
  private:
  uint32_t _internal_to_session_id() const;
  void _internal_set_to_session_id(uint32_t value);
  public:

  // uint32 msg_id = 3;
  void clear_msg_id();
  uint32_t msg_id() const;
  void set_msg_id(uint32_t value);
  private:
  uint32_t _internal_msg_id() const;
  void _internal_set_msg_id(uint32_t value);
  public:

  // uint32 create_time = 4;
  void clear_create_time();
  uint32_t create_time() const;
  void set_create_time(uint32_t value);
  private:
  uint32_t _internal_create_time() const;
  void _internal_set_create_time(uint32_t value);
  public:

  // .IM.BaseDefine.MsgType msg_type = 5;
  void clear_msg_type();
  ::IM::BaseDefine::MsgType msg_type() const;
  void set_msg_type(::IM::BaseDefine::MsgType value);
  private:
  ::IM::BaseDefine::MsgType _internal_msg_type() const;
  void _internal_set_msg_type(::IM::BaseDefine::MsgType value);
  public:

  // @@protoc_insertion_point(class_scope:IM.Message.IMMsgData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_data_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr attach_data_;
  uint32_t from_user_id_;
  uint32_t to_session_id_;
  uint32_t msg_id_;
  uint32_t create_time_;
  int msg_type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_IM_2eMessage_2eproto;
};
// -------------------------------------------------------------------

class IMMsgDataAck final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:IM.Message.IMMsgDataAck) */ {
 public:
  inline IMMsgDataAck() : IMMsgDataAck(nullptr) {}
  ~IMMsgDataAck() override;
  explicit constexpr IMMsgDataAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IMMsgDataAck(const IMMsgDataAck& from);
  IMMsgDataAck(IMMsgDataAck&& from) noexcept
    : IMMsgDataAck() {
    *this = ::std::move(from);
  }

  inline IMMsgDataAck& operator=(const IMMsgDataAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline IMMsgDataAck& operator=(IMMsgDataAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const IMMsgDataAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const IMMsgDataAck* internal_default_instance() {
    return reinterpret_cast<const IMMsgDataAck*>(
               &_IMMsgDataAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(IMMsgDataAck& a, IMMsgDataAck& b) {
    a.Swap(&b);
  }
  inline void Swap(IMMsgDataAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IMMsgDataAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IMMsgDataAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IMMsgDataAck>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const IMMsgDataAck& from);
  void MergeFrom(const IMMsgDataAck& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(IMMsgDataAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "IM.Message.IMMsgDataAck";
  }
  protected:
  explicit IMMsgDataAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserIdFieldNumber = 1,
    kSessionIdFieldNumber = 2,
    kMsgIdFieldNumber = 3,
    kSessionTypeFieldNumber = 4,
  };
  // uint32 user_id = 1;
  void clear_user_id();
  uint32_t user_id() const;
  void set_user_id(uint32_t value);
  private:
  uint32_t _internal_user_id() const;
  void _internal_set_user_id(uint32_t value);
  public:

  // uint32 session_id = 2;
  void clear_session_id();
  uint32_t session_id() const;
  void set_session_id(uint32_t value);
  private:
  uint32_t _internal_session_id() const;
  void _internal_set_session_id(uint32_t value);
  public:

  // uint32 msg_id = 3;
  void clear_msg_id();
  uint32_t msg_id() const;
  void set_msg_id(uint32_t value);
  private:
  uint32_t _internal_msg_id() const;
  void _internal_set_msg_id(uint32_t value);
  public:

  // .IM.BaseDefine.SessionType session_type = 4;
  void clear_session_type();
  ::IM::BaseDefine::SessionType session_type() const;
  void set_session_type(::IM::BaseDefine::SessionType value);
  private:
  ::IM::BaseDefine::SessionType _internal_session_type() const;
  void _internal_set_session_type(::IM::BaseDefine::SessionType value);
  public:

  // @@protoc_insertion_point(class_scope:IM.Message.IMMsgDataAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint32_t user_id_;
  uint32_t session_id_;
  uint32_t msg_id_;
  int session_type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_IM_2eMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IMMsgData

// uint32 from_user_id = 1;
inline void IMMsgData::clear_from_user_id() {
  from_user_id_ = 0u;
}
inline uint32_t IMMsgData::_internal_from_user_id() const {
  return from_user_id_;
}
inline uint32_t IMMsgData::from_user_id() const {
  // @@protoc_insertion_point(field_get:IM.Message.IMMsgData.from_user_id)
  return _internal_from_user_id();
}
inline void IMMsgData::_internal_set_from_user_id(uint32_t value) {
  
  from_user_id_ = value;
}
inline void IMMsgData::set_from_user_id(uint32_t value) {
  _internal_set_from_user_id(value);
  // @@protoc_insertion_point(field_set:IM.Message.IMMsgData.from_user_id)
}

// uint32 to_session_id = 2;
inline void IMMsgData::clear_to_session_id() {
  to_session_id_ = 0u;
}
inline uint32_t IMMsgData::_internal_to_session_id() const {
  return to_session_id_;
}
inline uint32_t IMMsgData::to_session_id() const {
  // @@protoc_insertion_point(field_get:IM.Message.IMMsgData.to_session_id)
  return _internal_to_session_id();
}
inline void IMMsgData::_internal_set_to_session_id(uint32_t value) {
  
  to_session_id_ = value;
}
inline void IMMsgData::set_to_session_id(uint32_t value) {
  _internal_set_to_session_id(value);
  // @@protoc_insertion_point(field_set:IM.Message.IMMsgData.to_session_id)
}

// uint32 msg_id = 3;
inline void IMMsgData::clear_msg_id() {
  msg_id_ = 0u;
}
inline uint32_t IMMsgData::_internal_msg_id() const {
  return msg_id_;
}
inline uint32_t IMMsgData::msg_id() const {
  // @@protoc_insertion_point(field_get:IM.Message.IMMsgData.msg_id)
  return _internal_msg_id();
}
inline void IMMsgData::_internal_set_msg_id(uint32_t value) {
  
  msg_id_ = value;
}
inline void IMMsgData::set_msg_id(uint32_t value) {
  _internal_set_msg_id(value);
  // @@protoc_insertion_point(field_set:IM.Message.IMMsgData.msg_id)
}

// uint32 create_time = 4;
inline void IMMsgData::clear_create_time() {
  create_time_ = 0u;
}
inline uint32_t IMMsgData::_internal_create_time() const {
  return create_time_;
}
inline uint32_t IMMsgData::create_time() const {
  // @@protoc_insertion_point(field_get:IM.Message.IMMsgData.create_time)
  return _internal_create_time();
}
inline void IMMsgData::_internal_set_create_time(uint32_t value) {
  
  create_time_ = value;
}
inline void IMMsgData::set_create_time(uint32_t value) {
  _internal_set_create_time(value);
  // @@protoc_insertion_point(field_set:IM.Message.IMMsgData.create_time)
}

// .IM.BaseDefine.MsgType msg_type = 5;
inline void IMMsgData::clear_msg_type() {
  msg_type_ = 0;
}
inline ::IM::BaseDefine::MsgType IMMsgData::_internal_msg_type() const {
  return static_cast< ::IM::BaseDefine::MsgType >(msg_type_);
}
inline ::IM::BaseDefine::MsgType IMMsgData::msg_type() const {
  // @@protoc_insertion_point(field_get:IM.Message.IMMsgData.msg_type)
  return _internal_msg_type();
}
inline void IMMsgData::_internal_set_msg_type(::IM::BaseDefine::MsgType value) {
  
  msg_type_ = value;
}
inline void IMMsgData::set_msg_type(::IM::BaseDefine::MsgType value) {
  _internal_set_msg_type(value);
  // @@protoc_insertion_point(field_set:IM.Message.IMMsgData.msg_type)
}

// bytes msg_data = 6;
inline void IMMsgData::clear_msg_data() {
  msg_data_.ClearToEmpty();
}
inline const std::string& IMMsgData::msg_data() const {
  // @@protoc_insertion_point(field_get:IM.Message.IMMsgData.msg_data)
  return _internal_msg_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IMMsgData::set_msg_data(ArgT0&& arg0, ArgT... args) {
 
 msg_data_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:IM.Message.IMMsgData.msg_data)
}
inline std::string* IMMsgData::mutable_msg_data() {
  std::string* _s = _internal_mutable_msg_data();
  // @@protoc_insertion_point(field_mutable:IM.Message.IMMsgData.msg_data)
  return _s;
}
inline const std::string& IMMsgData::_internal_msg_data() const {
  return msg_data_.Get();
}
inline void IMMsgData::_internal_set_msg_data(const std::string& value) {
  
  msg_data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* IMMsgData::_internal_mutable_msg_data() {
  
  return msg_data_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* IMMsgData::release_msg_data() {
  // @@protoc_insertion_point(field_release:IM.Message.IMMsgData.msg_data)
  return msg_data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void IMMsgData::set_allocated_msg_data(std::string* msg_data) {
  if (msg_data != nullptr) {
    
  } else {
    
  }
  msg_data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), msg_data,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (msg_data_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    msg_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:IM.Message.IMMsgData.msg_data)
}

// bytes attach_data = 20;
inline void IMMsgData::clear_attach_data() {
  attach_data_.ClearToEmpty();
}
inline const std::string& IMMsgData::attach_data() const {
  // @@protoc_insertion_point(field_get:IM.Message.IMMsgData.attach_data)
  return _internal_attach_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IMMsgData::set_attach_data(ArgT0&& arg0, ArgT... args) {
 
 attach_data_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:IM.Message.IMMsgData.attach_data)
}
inline std::string* IMMsgData::mutable_attach_data() {
  std::string* _s = _internal_mutable_attach_data();
  // @@protoc_insertion_point(field_mutable:IM.Message.IMMsgData.attach_data)
  return _s;
}
inline const std::string& IMMsgData::_internal_attach_data() const {
  return attach_data_.Get();
}
inline void IMMsgData::_internal_set_attach_data(const std::string& value) {
  
  attach_data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* IMMsgData::_internal_mutable_attach_data() {
  
  return attach_data_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* IMMsgData::release_attach_data() {
  // @@protoc_insertion_point(field_release:IM.Message.IMMsgData.attach_data)
  return attach_data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void IMMsgData::set_allocated_attach_data(std::string* attach_data) {
  if (attach_data != nullptr) {
    
  } else {
    
  }
  attach_data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), attach_data,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (attach_data_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    attach_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:IM.Message.IMMsgData.attach_data)
}

// -------------------------------------------------------------------

// IMMsgDataAck

// uint32 user_id = 1;
inline void IMMsgDataAck::clear_user_id() {
  user_id_ = 0u;
}
inline uint32_t IMMsgDataAck::_internal_user_id() const {
  return user_id_;
}
inline uint32_t IMMsgDataAck::user_id() const {
  // @@protoc_insertion_point(field_get:IM.Message.IMMsgDataAck.user_id)
  return _internal_user_id();
}
inline void IMMsgDataAck::_internal_set_user_id(uint32_t value) {
  
  user_id_ = value;
}
inline void IMMsgDataAck::set_user_id(uint32_t value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:IM.Message.IMMsgDataAck.user_id)
}

// uint32 session_id = 2;
inline void IMMsgDataAck::clear_session_id() {
  session_id_ = 0u;
}
inline uint32_t IMMsgDataAck::_internal_session_id() const {
  return session_id_;
}
inline uint32_t IMMsgDataAck::session_id() const {
  // @@protoc_insertion_point(field_get:IM.Message.IMMsgDataAck.session_id)
  return _internal_session_id();
}
inline void IMMsgDataAck::_internal_set_session_id(uint32_t value) {
  
  session_id_ = value;
}
inline void IMMsgDataAck::set_session_id(uint32_t value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:IM.Message.IMMsgDataAck.session_id)
}

// uint32 msg_id = 3;
inline void IMMsgDataAck::clear_msg_id() {
  msg_id_ = 0u;
}
inline uint32_t IMMsgDataAck::_internal_msg_id() const {
  return msg_id_;
}
inline uint32_t IMMsgDataAck::msg_id() const {
  // @@protoc_insertion_point(field_get:IM.Message.IMMsgDataAck.msg_id)
  return _internal_msg_id();
}
inline void IMMsgDataAck::_internal_set_msg_id(uint32_t value) {
  
  msg_id_ = value;
}
inline void IMMsgDataAck::set_msg_id(uint32_t value) {
  _internal_set_msg_id(value);
  // @@protoc_insertion_point(field_set:IM.Message.IMMsgDataAck.msg_id)
}

// .IM.BaseDefine.SessionType session_type = 4;
inline void IMMsgDataAck::clear_session_type() {
  session_type_ = 0;
}
inline ::IM::BaseDefine::SessionType IMMsgDataAck::_internal_session_type() const {
  return static_cast< ::IM::BaseDefine::SessionType >(session_type_);
}
inline ::IM::BaseDefine::SessionType IMMsgDataAck::session_type() const {
  // @@protoc_insertion_point(field_get:IM.Message.IMMsgDataAck.session_type)
  return _internal_session_type();
}
inline void IMMsgDataAck::_internal_set_session_type(::IM::BaseDefine::SessionType value) {
  
  session_type_ = value;
}
inline void IMMsgDataAck::set_session_type(::IM::BaseDefine::SessionType value) {
  _internal_set_session_type(value);
  // @@protoc_insertion_point(field_set:IM.Message.IMMsgDataAck.session_type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Message
}  // namespace IM

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_IM_2eMessage_2eproto
